# Generated by Django 4.0.6 on 2022-08-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='users',
            field=models.ManyToManyField(related_name='owned_by', through='ingredients.InStock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='instock',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='instock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='instock',
            unique_together={('ingredient', 'user')},
        ),
    ]
