# Generated by Django 4.1 on 2023-05-21 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_reciperating_maderecipe_likedrecipe_favouriterecipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouriterecipe',
            unique_together={('recipe', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='likedrecipe',
            unique_together={('recipe', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='maderecipe',
            unique_together={('recipe', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reciperating',
            unique_together={('recipe', 'user')},
        ),
    ]
